spring:
  datasource:
    url: jdbc:mysql://10.21.56.119:3306/qg24
    password: Qgstudio_123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  #扫描mapper的文件路径
  mapper-locations: classpath:mapper/*.xml
  #注册实体类
  type-aliases-package: com.qg24.po.entity
  #设置配置的日志输出信息
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true